<!DOCTYPE html>
<html lang="en">
<head>
    <title>API Documentation</title>
</head>
<body>
    <h1>Get list products</h1>
    <p>For getting list of products, you should complete GET request on http://${ip}/api/prod</p>
    <hr>
    <h1>Get product by id</h1>
    <p>For getting product by id, you should complete GET request on https://${ip}/api/prod/{id}</p>
    <hr>
    <h1>Add product</h1>
    <p>For adding product, you should complete POST request with json object in body on https://${ip}/api/prod/</p>
    <hr>
    <h1>Remove product by id</h1>
    <p>For removing product by id, you should complete DELETE request on https://${ip}/api/prod/{id}</p>
    <hr>
    <h1>Change product by id</h1>
    <p>For changing product by id, you should complete PUT request with json object(Product, which contains only changing properties) in body on https://${ip}/api/prod/{id}</p>
</body>
</html>