<!DOCTYPE html>
<html lang="ru">
<form action="/signup/create" method="post">
    Имя пользователя: <label>
        <input type="text" name="username">
    </label><br><br>
    e-mail: <label>
        <input type="email" name="email">
    </label><br><br>
    Пароль: <label>
        <input type="password" name="password">
    </label><br><br>
    <input type="submit" name="Зарегистрироваться">
</form>
</html>